everything = [
    {'link': 'http://www.iso.org/iso/home/standards/isoblahblah.htm',
     'name': 'ISO-blahblah',
     'date_created': '2013-07-14',
     'type': 'reference',
     'id': 322},
    {'name': 'cybersecurity framework',
     'date_created': 0,
     'type': 'root',
     'id': 192,
     'children': [193,
                  194,
                  195,
                  196,
                  197]},
    {'children': [198,
                  199,
                  203,
                  205],
     'name': 'Know',
     'date_created': '2013-07-09',
     'type': 'function',
     'id': 193,
     'description': 'Gaining the institutional understanding to identify what systems need to be protected, assess priority in light of organizational mission,and manage processes to achieve cost effective risk management goals'},
    {'children': [],
     'name': 'Prevent',
     'date_created': '2013-07-09',
     'type': 'function',
     'id': 194,
     'description': 'Categories of management, technical, and operational activities that enable the organization to decide on the appropriate outcome-based actions to ensure adequate protection against threats to business systems that support critical infrastructure components.'},
    {'children': [],
     'name': 'Detect',
     'date_created': '2013-07-09',
     'type': 'function',
     'id': 195,
     'description': 'Activities that identify (through ongoing monitoring or other means of observation) the presence of undesirable cyber risk events, and the processes to assess the potential impact of those events.'},
    {'children': [],
     'name': 'Respond',
     'date_created': '2013-07-09',
     'type': 'function',
     'id': 196,
     'description': 'Specific risk management decisions and activities enacted based upon previously implemented planning (from the Prevent function) relative to estimated impact.'},
    {'children': [],
     'name': 'Recover',
     'date_created': '2013-07-09',
     'type': 'function',
     'id': 197,
     'description': 'Categories of management, technical, and operational activities that restore services that have previously been impaired through an undesirable cybersecurity risk event.'},
    {'children': [231,
                  233,
                  234],
     'name': 'systems',
     'date_created': '2013-07-11',
     'type': 'category',
     'id': 198, 'description': 'Some text about systems and how they relate to the Know function. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
    {'children': [322,
                  323],
     'name': 'subcat1',
     'date_created': '2013-07-12',
     'type': 'subcategory',
     'id': 231,
     'description': 'Text about subcategory, lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.'}
]
